# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
podfile: Example/Podfile
before_install:
- gem install cocoapods 
- gem install xcpretty
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/AutoLinearLayoutView.xcworkspace -scheme AutoLinearLayoutView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

